cargo = ["atuin", "bacon", "bkt", "cargo-update", "metapac"]
winget = [
  "9NP355QT2SQB",                           # Azure VPN Client
  "AgileBits.1Password",
  "ArminOsaj.AutoDarkMode",
  "AutoHotkey.AutoHotkey",
  "Beeper.Beeper",
  "Docker.DockerDesktop",
  "Doist.Todoist",
  "Git.Git",
  "JanetLang.Janet",
  "JetBrains.Rider",
  "Logseq.Logseq",
  "Martchus.syncthingtray",
  "Microsoft.AppInstaller",
  "Microsoft.Azure.CosmosEmulator",
  "Microsoft.Edge",
  "Microsoft.Office",
  "Microsoft.PowerShell",
  "Microsoft.Sysinternals.Autoruns",
  "Microsoft.Teams",
  "Microsoft.UI.Xaml.2.7",
  "Microsoft.UI.Xaml.2.8",
  "Microsoft.VCLibs.Desktop.14",
  "Microsoft.VCRedist.2015+.x64",
  "Microsoft.VCRedist.2015+.x86",
  "Microsoft.VisualStudio.2022.BuildTools",
  "Microsoft.VisualStudioCode",
  "Microsoft.WindowsApp",
  "Microsoft.WindowsTerminal",
  "Mozilla.Firefox",
  "Neovim.Neovim",
  "Notion.Notion",
  "Nushell.Nushell",
  "OpenWhisperSystems.Signal",
  "Oven-sh.Bun",
  "Raycast.Raycast",
  "Rustlang.Rustup",
  "ajeetdsouza.zoxide",
  "flux.flux",
  "topgrade-rs.topgrade",
  "wez.wezterm",
  "xanderfrangos.twinkletray", "rsteube.Carapace", "Codeium.Windsurf",
]

scoop = [
  ".sm/temurin-jdk",
  "extras/autohotkey",
  "extras/bulk-crap-uninstaller",
  "extras/copyq",
  "extras/lazygit",
  "extras/neovide",
  "extras/riff",
  "extras/spotify",
  "extras/xan",
  "main/7zip",
  "main/aria2",
  "main/azure-cli",
  "main/bottom",
  "main/bun",
  "main/cacert",
  "main/chezmoi",
  "main/curlie",
  "main/dark",
  "main/delta",
  "main/deno",
  "main/difftastic",
  "main/dotnet-sdk",
  "main/eza",
  "main/fd",
  "main/fx",
  "main/fzf",
  "main/gawk",
  "main/gcc",
  "main/gh",
  "main/go",
  "main/golangci-lint",
  "main/gzip",
  "main/hyperfine",
  "main/innounp",
  "main/jj",
  "main/jq",
  "main/just",
  "main/lua",
  "main/luarocks",
  "main/make",
  "main/nodejs-lts",
  "main/oh-my-posh",
  "main/openssl",
  "main/ouch",
  "main/python",
  "main/ripgrep",
  "main/tealdeer",
  "main/typos",
  "main/unzip",
  "main/uv",
  "main/vale",
  "main/wget",
  "main/win32yank",
  "main/yq",
  "nerd-fonts/JetBrainsMono-NF-Mono",
  "nerd-fonts/JetBrainsMono-NF-Propo",
  "nerd-fonts/NerdFontsSymbolsOnly", "main/glow",
]
