# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/
matches:
  - trigger: ";a"
    replace: "å"
    propagate_case: true

  - trigger: ";o"
    replace: "ø"
    propagate_case: true

  - trigger: ";e"
    replace: "æ"
    propagate_case: true

  - trigger: ";m"
    replace: "—"

  - trigger: ";n"
    replace: "–"

  - trigger: ";jf"
    replace: "jensfredskov"

  - trigger: ";p"
    replace: "jensfredskov@gmail.com"

  - trigger: ";w"
    replace: "jens.fredskov@nekohealth.com"

  - trigger: ";td"
    replace: "TODO: ({{today}} - jens)"
    vars:
      - name: today
        type: date
        params:
          format: "%F"
