after-login-command = []
after-startup-command = [
  'exec-and-forget borders style=round width=5 active_color=0xff618a57 inactive_color=0x00000000',
]
exec-on-workspace-change = []

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'
default-root-container-orientation = 'vertical'

key-mapping.preset = 'qwerty'

automatically-unhide-macos-hidden-apps = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 9
inner.vertical = 9
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[mode.main.binding]
ctrl-alt-shift-e = 'exec-and-forget ~/.local/bin/,open-or-focus-browser Firefox'
ctrl-alt-shift-w = 'exec-and-forget open -a Wezterm'
ctrl-alt-shift-b = 'exec-and-forget open -a "Beeper Desktop"'
ctrl-alt-shift-s = 'exec-and-forget open -a Signal'
ctrl-alt-shift-o = 'exec-and-forget open -a Logseq'
ctrl-alt-shift-t = 'exec-and-forget open -a "Microsoft Teams"'
ctrl-alt-shift-r = 'exec-and-forget open -a Rider'
ctrl-alt-shift-p = 'exec-and-forget open -a "Super Productivity"'
ctrl-alt-shift-c = 'exec-and-forget open -a VSCodium'
cmd-esc = 'exec-and-forget open -a "Mission Control"'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-period = 'layout tiles horizontal vertical'
alt-comma = 'layout v_accordion'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left --boundaries all-monitors-outer-frame'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right --boundaries all-monitors-outer-frame'

alt-u = 'focus down --boundaries-action wrap-around-the-workspace'
alt-i = 'focus up --boundaries-action wrap-around-the-workspace'

alt-shift-h = 'exec-and-forget ~/.local/bin/,aerospace-move-window left'
alt-shift-j = 'exec-and-forget ~/.local/bin/,aerospace-move-window down'
alt-shift-k = 'exec-and-forget ~/.local/bin/,aerospace-move-window up'
alt-shift-l = 'exec-and-forget ~/.local/bin/,aerospace-move-window right'

alt-semicolon = 'exec-and-forget ~/.local/bin/,aerospace-resize-window "0.70"'
alt-shift-semicolon = 'exec-and-forget ~/.local/bin/,aerospace-resize-window "0.30"'
alt-slash = 'balance-sizes'

alt-shift-r = ['flatten-workspace-tree', 'layout v_accordion']

[workspace-to-monitor-force-assignment]
1 = 'built-in'
