after-login-command = []
after-startup-command = [
  'exec-and-forget borders style=round width=5 active_color=0xff618a57 inactive_color=0x00000000',
]
exec-on-workspace-change = []

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'
default-root-container-orientation = 'vertical'

key-mapping.preset = 'qwerty'

automatically-unhide-macos-hidden-apps = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 9
inner.vertical = 9
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[mode.main.binding]
ctrl-alt-shift-e = 'exec-and-forget ~/.local/bin/,open-or-focus-browser Firefox'
ctrl-alt-shift-w = 'exec-and-forget open -a Wezterm'
ctrl-alt-shift-b = 'exec-and-forget open -a "Beeper Desktop"'
ctrl-alt-shift-s = 'exec-and-forget open -a Signal'
ctrl-alt-shift-o = 'exec-and-forget open -a Logseq'
ctrl-alt-shift-t = 'exec-and-forget open -a "Microsoft Teams"'
ctrl-alt-shift-c = 'exec-and-forget open -a "Visual Studio Code"'
ctrl-alt-shift-r = 'exec-and-forget open -a Rider'
cmd-esc = 'exec-and-forget open -a "Mission Control"'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
# alt-period = 'layout tiles horizontal vertical'
alt-comma = 'layout v_accordion'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
# alt-h = 'focus left --boundaries all-monitors-outer-frame'
# alt-j = 'focus down'
# alt-k = 'focus up'
# alt-l = 'focus right --boundaries all-monitors-outer-frame'
alt-h = 'exec-and-forget ~/.local/bin/,aerospace-move-window left'
alt-j = 'exec-and-forget ~/.local/bin/,aerospace-move-window down'
alt-k = 'exec-and-forget ~/.local/bin/,aerospace-move-window up'
alt-l = 'exec-and-forget ~/.local/bin/,aerospace-move-window right'

alt-u = 'focus down --boundaries-action wrap-around-the-workspace'
alt-i = 'focus up --boundaries-action wrap-around-the-workspace'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left --boundaries all-monitors-outer-frame'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right --boundaries all-monitors-outer-frame'

# ctrl-shift-h = ['join-with left', 'layout v_accordion']
# ctrl-shift-j = ['join-with down']
# ctrl-shift-k = ['join-with up']
# ctrl-shift-l = ['join-with right', 'layout v_accordion']

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-semicolon = 'exec-and-forget ~/.local/bin/,aerospace-resize-window "0.70"'
alt-shift-semicolon = 'exec-and-forget ~/.local/bin/,aerospace-resize-window "0.30"'
alt-slash = 'balance-sizes'

# alt-semicolon = 'mode service'
# [mode.service.binding]
# esc = ['reload-config', 'mode main']
# r = ['flatten-workspace-tree', 'mode main']
# f = ['layout floating tiling', 'mode main']
# b = [
#   'exec-and-forget borders style=round width=5 hidpi=off active_color=0xff618a57 inactive_color=0x00000000',
#   'mode main',
# ]

# [[on-window-detected]]
# if.app-id = 'org.mozilla.firefoxdeveloperedition'
# if.window-title-regex-substring = 'Picture-in-Picture'
# run = ['layout floating']
#
# [workspace-to-monitor-force-assignment]
# 1 = 'built-in'
