after-login-command = []
after-startup-command = [
  'exec-and-forget borders style=round width=5 hidpi=off active_color=0xff618a57 inactive_color=0x00000000',
]
exec-on-workspace-change = ['~/.local/bin/,pip-all-workspaces']

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'
default-root-container-orientation = 'vertical'

key-mapping.preset = 'qwerty'

automatically-unhide-macos-hidden-apps = true

[gaps]
inner.horizontal = 9
inner.vertical = 9
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[mode.main.binding]
ctrl-alt-shift-e = 'exec-and-forget ~/.local/bin/,open-or-focus-browser Firefox'
ctrl-alt-shift-w = 'exec-and-forget open -a Wezterm'
ctrl-alt-shift-b = 'exec-and-forget open -a "Beeper Desktop"'
ctrl-alt-shift-s = 'exec-and-forget open -a Signal'
ctrl-alt-shift-o = 'exec-and-forget open -a Logseq'
ctrl-alt-shift-t = 'exec-and-forget open -a "Microsoft Teams"'
ctrl-alt-shift-c = 'exec-and-forget open -a "Visual Studio Code"'
cmd-esc = 'exec-and-forget open -a "Mission Control"'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left --boundaries all-monitors-outer-frame'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right --boundaries all-monitors-outer-frame'

alt-u = 'focus down'
alt-i = 'focus up'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left --boundaries all-monitors-outer-frame'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right --boundaries all-monitors-outer-frame'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
ctrl-shift-equal = 'balance-sizes'

alt-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
b = [
  'exec-and-forget borders style=round width=5 hidpi=off active_color=0xff618a57 inactive_color=0x00000000',
  'mode main',
]
h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'org.mozilla.firefoxdeveloperedition'
if.window-title-regex-substring = 'Picture-in-Picture'
run = ['layout floating']
#
[workspace-to-monitor-force-assignment]
1 = 'built-in'
