"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Jens Fredskov"
email = "jsfr@users.noreply.github.com"

[revset-aliases]
"closest_bookmark(to)" = 'heads(::to & (bookmarks() ~ (bookmarks(exact:"main") | bookmarks(exact:"master"))))'
"immutable_heads()" = "builtin_immutable_heads() | (remote_bookmarks() ~ mine())"

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
re = ["restore"]
rb = ["rebase"]
g = ["git"]
f = ["git", "fetch"]
p = ["git", "push", "--allow-new"]
s = ["st"]
e = ["edit"]
d = ["diff"]
n = ["new"]
nt = ["new", "-r", "trunk()"]

[ui]
default-command = "log"

[git]
auto-local-bookmark = true
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
