"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Jens Fredskov"
email = "jsfr@users.noreply.github.com"

[revset-aliases]
"closest_bookmark(to)" = 'heads(::to & (bookmarks() ~ (bookmarks(exact:"main") | bookmarks(exact:"master"))))'
"immutable_heads()" = "builtin_immutable_heads() | (remote_bookmarks() ~ mine())"

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
tug-trunk = ["bookmark", "move", "--from", "trunk()", "--to", "@-"]
f = ["git", "fetch"]
p = ["git", "push", "--allow-new"]
s = ["st"]
e = ["edit"]
d = ["diff"]
n = ["new"]
nt = ["new", "-r", "trunk()"]
rebase-trunk = ["rebase", "-b", "closest_bookmark(@)", "-d", "trunk()"]
lc = ["log", "-T", "builtin_log_compact"]

[ui]
default-command = "log"

[git]
auto-local-bookmark = true
# Prevent pushing work in progress
private-commits = "description(glob:'wip:*')"

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[templates]
# log_node = '''
#   label("node",
#     coalesce(
#       if(!self, label("elided", "~")),
#       if(current_working_copy, label("working_copy", "@")),
#       if(conflict, label("conflict", "×")),
#       if(immutable, label("immutable", "*")),
#       label("normal", "·")
#     )
#   )
# '''
log = '''
  if(root,
    format_root_commit(self),
    label(if(current_working_copy, "working_copy"),
      concat(
        separate(" ",
          format_short_change_id_with_hidden_and_divergent_info(self),
          bookmarks,
          tags,
          working_copies,
          if(git_head, label("git_head", "HEAD")),
          if(conflict, label("conflict", "conflict")),
          if(empty, label("empty", "(empty)")),
          if(description,
            description.first_line(),
            label(if(empty, "empty"), description_placeholder),
          ),
        ) ++ "\n",
      ),
    )
  )
'''

# disable pagination for `jj status`, use `delta` for `jj diff` and `jj show`
[[--scope]]
--when.commands = ["status"]
[--scope.ui]
paginate = "never"

[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = "delta"
diff-formatter = ":git"
