local function set_options(options)
    for key, value in pairs(options) do
        vim.opt[key] = value
    end
end

set_options({
    autowrite = true,
    background = "dark",
    backup = true,
    breakindent = true,
    clipboard = "unnamedplus,unnamed",
    cursorline = true,
    expandtab = true,
    hidden = true,
    ignorecase = true,
    inccommand = "split",
    joinspaces = false,
    linespace = 0,
    list = true,
    listchars = "tab:→ ,eol:↵,trail:·,extends:↷,precedes:↶",
    magic = true,
    matchtime = 5,
    mouse = "a",
    number = true,
    pumheight = 20,
    relativenumber = true,
    report = 0,
    ruler = true,
    scrolljump = 5,
    scrolloff = 10,
    shiftwidth = 4,
    shortmess = "atOI",
    showbreak = "↳\\_",
    showcmd = true,
    showmatch = true,
    showmode = false,
    smartcase = true,
    softtabstop = 4,
    spell = false,
    splitbelow = true,
    splitkeep = "screen",
    splitright = true,
    swapfile = false,
    tabstop = 4,
    termguicolors = true,
    textwidth = 0,
    undofile = true,
    undolevels = 1000,
    undoreload = 10000,
    updatetime = 2000,
    wildmode = "list:longest,full",
    winminheight = 0,
    wrap = true,
    undodir = "/tmp//," .. vim.fs.normalize("~/.undodir"),
    backupdir = "/tmp//," .. vim.fs.normalize("~/.backupdir"),
    directory = "/tmp//," .. vim.fs.normalize("~/.swapdir"),
})
